# Generated by Django 6.0.4 on 2026-05-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
